"""initial_schema

Revision ID: b3e502be1b9f
Revises: 
Create Date: 2026-06-12 18:47:32.089376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e502be1b9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_provider_config', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_llm_provider_config_is_default'), ['is_default'], unique=False)

    with op.batch_alter_table('notification_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_job_lease_token'), ['lease_token'], unique=False)

    with op.batch_alter_table('source_health', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('topic_cluster', schema=None) as batch_op:
        batch_op.alter_column('cluster_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_topic_cluster_topic_key'), ['topic_key'], unique=True)

    with op.batch_alter_table('x_account', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'watch'"))
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'manual'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x_account', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'manual'"))
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'watch'"))

    with op.batch_alter_table('topic_cluster', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_cluster_topic_key'))
        batch_op.alter_column('cluster_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('source_health', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('notification_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_job_lease_token'))

    with op.batch_alter_table('llm_provider_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_provider_config_is_default'))
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
